<?php
/**
 * Created by PhpStorm.
 * User: sau
 * Date: 26.03.18
 * Time: 7:48
 */

use Joomla\CMS\Form\FormField;

/**
 * Class FormFieldASMLayout
 */
class FormFieldASMLayout extends FormField {

	protected function getInput() {
		echo $this->fieldname;

		return parent::getInput(); // TODO: Change the autogenerated stub
	}
}
