<?php

use Joomla\CMS\MVC\View\HtmlView;

/**
 * Created by PhpStorm.
 * User: sau
 * Date: 25.03.18
 * Time: 23:09
 */
class ASMViewPage extends HtmlView {
	/**
	 * Current page data
	 *
	 * @var object
	 * @since 1.0
	 */
	protected $item;

	public function display( $tpl = null ) {
		$this->item = $this->get( 'Item' );



		return parent::display( $tpl ); // TODO: Change the autogenerated stub
	}
}