<?php
/**
 * Created by PhpStorm.
 * User: sau
 * Date: 25.03.18
 * Time: 23:09
 */

class ASMViewPage extends JViewHtml {
	public function render() {
		return parent::render(); // TODO: Change the autogenerated stub
	}
}