<?php
/**
 * Created by PhpStorm.
 * User: sau
 * Date: 21.03.18
 * Time: 11:09
 */

use Joomla\CMS\MVC\Controller\BaseController;

/**
 * Class ASMController
 * @since 1.0
 */
class ASMController extends BaseController {
	protected $default_view = 'page';

	public function display( $cachable = false, $urlparams = array() ) {

		return parent::display( $cachable, $urlparams ); // TODO: Change the autogenerated stub
	}
}