<?php
/**
 * Created by PhpStorm.
 * User: sau
 * Date: 21.03.18
 * Time: 11:09
 *
 * @package     Joomla.Administrator
 * @subpackage  com_asm
 *
 * @copyright   Copyright (C) 2005 - 2018 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Controller\BaseController;

class ASMController extends BaseController {
	/**
	 * @param bool  $cachable
	 * @param array $urlparams
	 *
	 * @return JControllerLegacy
	 * @throws Exception
	 *
	 * @since 1.0
	 */
	public function display ( $cachable = false, $urlparams = array() ) {
		$input = Factory::getApplication()->input;
		$input->set('view', $input->getCmd('view', 'Pages'));

		return parent::display($cachable, $urlparams); // TODO: Change the autogenerated stub
	}
}